digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

lowercase letter = "a" | "b" | "c" | "d" | "e" | "f" | "g"
                 | "h" | "i" | "j" | "k" | "l" | "m" | "n"
                 | "o" | "p" | "q" | "r" | "s" | "t" | "u"
                 | "v" | "w" | "x" | "y" | "z" ;

uppercase letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
                 | "H" | "I" | "J" | "K" | "L" | "M" | "N"
                 | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
                 | "V" | "W" | "X" | "Y" | "Z"

letter = lowercase letter | uppercase letter;

number = [ "-" ] , { digit }+ , [ "." { digit }+ ] ;

identifier = lowercase letter | underscore, { letter | digit } ;

operator = "*" | "/" | "%"  | "+"  | "-"  | "<<" | ">>"
         | "<" | ">" | "<=" | ">=" | "==" | "!=" | "&"
         | "^" | "|" | "&&" | "||"

constant = "pi" | "e" | "tau" | "true" | "false"

function = identifier, "(" param list ")"

param list = ( ) | ( operand { ",", operand } )

operand = number | constant | function

expression = { operand, operator }, operand